---
apiVersion: v1
kind: Pod
metadata:
  name: gop-file-server
spec:
  containers:
  - name: gop-file-server
    image: kodekloud/fileserver
    volumeMounts:
      - name: data-store
        mountPath: /web
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31200