apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: jekyll
spec:
  type: NodePort
  selector:
    run: jekyll
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 4000
    nodePort: 30097
