---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-service
spec:
  type: NodePort
  selector:
    app: vote
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
    nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: vote-deployment
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: kodekloud/examplevotingapp_vote:before